-- MySQL Script generated by MySQL Workbench
-- Mon May 27 23:23:57 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbtaxi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbtaxi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbtaxi` DEFAULT CHARACTER SET utf8 ;
USE `dbtaxi` ;

-- -----------------------------------------------------
-- Table `dbtaxi`.`admin_postos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtaxi`.`admin_postos` (
  `id_admin` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `numeroTel` VARCHAR(30) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `local_cidade` VARCHAR(45) NOT NULL,
  `idade` DATE NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_admin`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `numeroTel_UNIQUE` (`numeroTel` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtaxi`.`posto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtaxi`.`posto` (
  `local_cidade` VARCHAR(100) NOT NULL,
  `id_posto` INT NOT NULL AUTO_INCREMENT,
  `numero_Tel_Posto` VARCHAR(30) NOT NULL,
  `local_estado` VARCHAR(45) NOT NULL,
  `admin_postos_id_admin` INT NOT NULL,
  `data_criacao` DATE NOT NULL,
  `capacidade` INT NOT NULL,
  `CEP` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id_posto`),
  UNIQUE INDEX `id_posto_UNIQUE` (`id_posto` ASC) VISIBLE,
  INDEX `fk_posto_admin_postos1_idx` (`admin_postos_id_admin` ASC) VISIBLE,
  CONSTRAINT `fk_posto_admin_postos1`
    FOREIGN KEY (`admin_postos_id_admin`)
    REFERENCES `dbtaxi`.`admin_postos` (`id_admin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtaxi`.`membro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtaxi`.`membro` (
  `id_taxista` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `numeroTel` VARCHAR(30) NOT NULL,
  `placa_carro` VARCHAR(7) NOT NULL,
  `idade` DATE NOT NULL,
  `admin_posto` TINYINT NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `posto_id_posto` INT NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_taxista`),
  UNIQUE INDEX `id_taxista_UNIQUE` (`id_taxista` ASC) VISIBLE,
  UNIQUE INDEX `numeroTel_UNIQUE` (`numeroTel` ASC) VISIBLE,
  UNIQUE INDEX `placa_carro_UNIQUE` (`placa_carro` ASC) VISIBLE,
  UNIQUE INDEX `admin_posto_UNIQUE` (`admin_posto` ASC) VISIBLE,
  INDEX `fk_membro_posto1_idx` (`posto_id_posto` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  CONSTRAINT `fk_membro_posto1`
    FOREIGN KEY (`posto_id_posto`)
    REFERENCES `dbtaxi`.`posto` (`id_posto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
